version: '3'

services:
    z-pump:
        image: ruppreca/gpiocontrol:latest
        container_name: gpiocontrol
        restart: always
        user: 1000:993
        volumes:
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
            - /sys/class/pwm/pwmchip0:/sys/class/pwm/pwmchip0:rw
            - /var/log/gpiocontrol:/var/log/gpiocontrol:rw
